[package]
name = "app_engine"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
egui = "0.34"
taffy = "0.10"
mlua = { version = "0.10", features = ["lua54", "vendored"] }
loro = "1.12.0"
rich_text = { path = "../rich_text" }
text_edit = { path = "../text_edit" }
