local classes = {
	[1] = {
		label = "Class 1",
		intro = "Notice what we can see, put familiar actions in order, and care for things we share.",
		exercises = {
			source = {
				id = "c1-source-photo-sapling",
				title = "Look closely",
				prompt = "What can we say from this picture note alone?",
				source_label = "Picture note",
				source = "A photograph shows three children placing a small sapling in soil in a school courtyard.",
				choices = {
					{ id = "planting", text = "The children were planting a sapling." },
					{ id = "happy", text = "Every child in the school felt happy." },
					{ id = "holiday", text = "The picture was taken on a national holiday." },
				},
				answer = "planting",
				clue = "Choose only what the picture note lets us see directly.",
				explanation = "The people, sapling, soil, and action are visible. Feelings and the date would need more evidence.",
			},
			order = {
				id = "c1-order-family-story",
				title = "Make a family story strip",
				prompt = "Drag the cards onto the timeline in the order that helps you learn and share a memory.",
				steps = {
					{ id = "ask", text = "Ask an older family member about one memory." },
					{ id = "listen", text = "Listen carefully to the story." },
					{ id = "draw", text = "Draw the parts in story order." },
				},
				start = { "draw", "ask", "listen" },
				clue = "A good story strip begins by asking, then listening.",
				explanation = "First we ask, next we listen, and then we can draw the memory in order.",
			},
			civics = {
				id = "c1-civic-shared-crayons",
				title = "Our shared crayons",
				prompt = "Which actions help everyone use the class crayon box? Choose all that help.",
				choices = {
					{ id = "return", text = "Return crayons after using them." },
					{ id = "turn", text = "Wait for a turn when a colour is busy." },
					{ id = "hide", text = "Hide favourite colours in a desk." },
				},
				answers = { "return", "turn" },
				clue = "Think about whether every classmate still gets a fair chance.",
				explanation = "Returning shared things and taking turns make the box useful to everyone. Hiding crayons does not.",
			},
		},
	},
	[2] = {
		label = "Class 2",
		intro = "Read a small record, arrange a simple inquiry, and make shared places welcoming.",
		exercises = {
			source = {
				id = "c2-source-postcard-train",
				title = "Read a postcard",
				prompt = "Which idea is directly supported by the postcard?",
				source_label = "Postcard, dated 1960",
				source = "Dear Meena, We reached Jaipur by train this morning. The station was crowded. Love, Tara.",
				choices = {
					{ id = "train", text = "Tara travelled to Jaipur by train." },
					{ id = "first", text = "This was Tara's first train journey." },
					{ id = "all", text = "All stations were crowded in 1960." },
				},
				answer = "train",
				clue = "Look for an idea stated in the writer's own words.",
				explanation = "The writer says “by train.” The card does not tell us whether it was a first journey or describe every station.",
			},
			order = {
				id = "c2-order-object-history",
				title = "Learn from an old object",
				prompt = "Drag the cards onto the timeline to rebuild this inquiry plan. Each step uses what comes before it.",
				steps = {
					{ id = "choose", text = "Choose an old object with permission." },
					{ id = "observe", text = "Notice its material, marks, and shape." },
					{ id = "ask", text = "Ask about the marks you noticed and how the object was used." },
					{ id = "record", text = "Record what you observed and what the answer added." },
				},
				start = { "record", "ask", "choose", "observe" },
				clue = "Begin with permission, then observe so your question can use what you noticed.",
				explanation = "Permission comes first. Observing helps form a useful question, and the final record brings both kinds of evidence together.",
			},
			civics = {
				id = "c2-civic-neighbourhood-park",
				title = "A park for everyone",
				prompt = "Which choices help people share a neighbourhood park? Choose all that help.",
				choices = {
					{ id = "bin", text = "Put litter in a bin or carry it home." },
					{ id = "path", text = "Keep the walking path clear." },
					{ id = "shout", text = "Shout at younger children to make them leave." },
					{ id = "turn", text = "Take turns on busy play equipment." },
				},
				answers = { "bin", "path", "turn" },
				clue = "Choose actions that care for the place and for other people.",
				explanation = "Managing litter, keeping paths clear, and taking turns support shared use. Chasing others away does not.",
			},
		},
	},
	[3] = {
		label = "Class 3",
		intro = "Combine clues, organise a fair group process, and include different needs.",
		exercises = {
			source = {
				id = "c3-source-water-pot",
				title = "Use two clues together",
				prompt = "Which conclusion is best supported by both sources?",
				source_label = "Object + oral account",
				source = "Object: a brass water pot with a worn handle. Oral account: “As a child, I carried water from the community well in a pot like this.”",
				choices = {
					{ id = "carried", text = "The speaker carried water from a community well in a pot like this." },
					{ id = "everyone", text = "Every family in India used the same kind of pot." },
					{ id = "age", text = "The worn handle proves the exact age of the pot." },
				},
				answer = "carried",
				clue = "Find the claim where the object and the speaker's memory support each other.",
				explanation = "The object shows this kind of pot, and the speaker directly describes carrying water in one like it. The sources cannot tell us about every family or prove an exact date.",
			},
			order = {
				id = "c3-order-class-plan",
				title = "Make a class plan",
				prompt = "Drag the cards onto the timeline to rebuild this class plan. Each step prepares the next one.",
				steps = {
					{ id = "name", text = "Name a shared problem the class has noticed." },
					{ id = "listen", text = "Listen to different ideas about that named problem." },
					{ id = "choose", text = "Use those ideas to choose a fair, practical step." },
					{ id = "review", text = "Try the chosen step and review how it worked." },
				},
				start = { "choose", "review", "listen", "name" },
				clue = "Name the problem first; each later step should use what the class learned before it.",
				explanation = "The named problem focuses the discussion, the ideas inform the choice, and reviewing the chosen step helps the class improve it.",
			},
			civics = {
				id = "c3-civic-inclusive-game",
				title = "Change the game",
				prompt = "A classmate cannot easily use one hand today. Which responses support participation?",
				choices = {
					{ id = "ask", text = "Ask what change would help them join." },
					{ id = "rules", text = "Adapt the rules for the whole group if needed." },
					{ id = "watch", text = "Tell them to watch while everyone else plays." },
					{ id = "decide", text = "Choose for them without asking." },
				},
				answers = { "ask", "rules" },
				clue = "Inclusion means listening to the person and removing a barrier.",
				explanation = "Asking and adapting support dignity and participation. Excluding someone or deciding without them does not.",
			},
		},
	},
	[4] = {
		label = "Class 4",
		intro = "Compare accounts, test an explanation, and design fair rules for shared resources.",
		exercises = {
			source = {
				id = "c4-source-rain-market",
				title = "Compare two records",
				prompt = "What conclusion do both records support?",
				source_label = "Diary + local weekly paper",
				source = "Diary: “After the heavy rain, our cart reached the market late on the muddy road.” Paper: “Rain disrupted several deliveries to the town market this week.”",
				choices = {
					{ id = "delay", text = "Heavy rain affected some journeys and market deliveries." },
					{ id = "closed", text = "The market was closed for the whole month." },
					{ id = "country", text = "Every road in the country was muddy." },
				},
				answer = "delay",
				clue = "Look for the overlap between one person's diary and the wider report.",
				explanation = "Both mention rain and disrupted travel or delivery. Neither supports a month-long closure or a claim about every road.",
			},
			order = {
				id = "c4-order-history-inquiry",
				title = "Build an evidence-based explanation",
				prompt = "Drag the evidence cards into a careful history inquiry timeline.",
				steps = {
					{ id = "question", text = "Write a focused question about the past." },
					{ id = "gather", text = "Gather relevant objects, images, or accounts." },
					{ id = "origin", text = "Note who made each source, when, and why." },
					{ id = "compare", text = "Compare what the sources agree and disagree about." },
					{ id = "explain", text = "Write an explanation and name its limits." },
				},
				start = { "compare", "question", "explain", "gather", "origin" },
				clue = "Begin with a question; understand each source before comparing it.",
				explanation = "A focused question guides the search. Source origins and comparison help produce a supported explanation with honest limits.",
			},
			civics = {
				id = "c4-civic-library-rule",
				title = "A fair class library",
				prompt = "Books are often returned late. Which parts belong in a fair class rule?",
				choices = {
					{ id = "clear", text = "Use the same clear borrowing period for everyone." },
					{ id = "remind", text = "Give a reminder and a way to request more time." },
					{ id = "favourite", text = "Let only top scorers borrow popular books." },
					{ id = "review", text = "Review the rule if it creates new problems." },
				},
				answers = { "clear", "remind", "review" },
				clue = "A fair rule is clear, applies equally, and can be improved after feedback.",
				explanation = "A common rule, a reasonable request process, and review support fairness. Marks should not decide access to shared books.",
			},
		},
	},
	[5] = {
		label = "Class 5",
		intro = "Weigh different viewpoints, structure an inquiry, and apply dignity and equality in daily life.",
		exercises = {
			source = {
				id = "c5-source-public-well",
				title = "Hold two truths together",
				prompt = "Which explanation uses both sources without claiming too much?",
				source_label = "Meeting note + household letter",
				source = "Meeting note: a new public well was approved near the eastern lane. Letter: “The new well shortens our walk, though the morning queue is still long.”",
				choices = {
					{ id = "mixed", text = "The new well improved access for this household, while queues remained a problem." },
					{ id = "solved", text = "The new well solved every water problem in the area." },
					{ id = "failed", text = "The well brought no benefit because a queue remained." },
				},
				answer = "mixed",
				clue = "Keep the improvement and the remaining difficulty in the same explanation.",
				explanation = "The letter reports a shorter walk and a long queue. Evidence can show improvement without proving that every problem ended.",
			},
			order = {
				id = "c5-order-crossing-inquiry",
				title = "Raise a local concern constructively",
				prompt = "Drag the cards onto the timeline to rebuild this inquiry plan. Each step uses information from the one before it.",
				steps = {
					{ id = "observe", text = "Observe safely and record when the crossing is busiest." },
					{ id = "viewpoints", text = "Use those observations when gathering views from walkers, residents, and drivers." },
					{ id = "proposal", text = "Use the timings and viewpoints to develop a practical proposal." },
					{ id = "share", text = "Share the evidence, concern, and proposal with the relevant local body." },
					{ id = "follow", text = "Follow up respectfully and review any response." },
				},
				start = { "share", "observe", "follow", "proposal", "viewpoints" },
				clue = "Start with safe observation; each later step should use information already gathered.",
				explanation = "The recorded timings guide the viewpoints inquiry, and both support a proposal. Sharing it and following up create a constructive process; exact official procedures may vary.",
			},
			civics = {
				id = "c5-civic-language-dignity",
				title = "Belonging in a new class",
				prompt = "A new classmate speaks a different home language. Which actions support dignity and equal participation?",
				choices = {
					{ id = "invite", text = "Invite their ideas and give time to respond." },
					{ id = "explain", text = "Explain unfamiliar class routines without teasing." },
					{ id = "ban", text = "Demand that they never use their home language." },
					{ id = "partner", text = "Offer a supportive peer partner if they want one." },
					{ id = "ignore", text = "Leave them out until their speech matches everyone else's." },
				},
				answers = { "invite", "explain", "partner" },
				clue = "Choose actions that remove barriers while respecting the learner's voice and identity.",
				explanation = "Patience, clear support, and a welcomed partner can widen participation. Language difference is not a reason to silence or exclude someone.",
			},
		},
	},
}

return {
	classes = classes,
	mechanics = {
		{ id = "source", label = "Source detective", short = "Evidence" },
		{ id = "order", label = "Put it in order", short = "Order" },
		{ id = "civics", label = "Together choices", short = "Civics" },
	},
}
