local classes = {
	{
		class = 1,
		tagline = "Words I know",
		colour = "#e8734a",
		exercises = {
			{
				id = "c1-choose-naming-word",
				kind = "choose",
				title = "Find the naming word",
				skill = "Naming words",
				prompt = "Asha sings. Which word names a person?",
				options = { "sings", "Asha", "softly" },
				answer = 2,
				clue = "Look for the name in the little sentence.",
				explanation = "Asha is the name of a person, so it is a naming word.",
			},
			{
				id = "c1-build-kite",
				kind = "build",
				title = "Build a clear sentence",
				skill = "Sentence order",
				prompt = "Drag the cards to say something about the kite.",
				tokens = { "red.", "kite", "The", "is" },
				answer = { "The", "kite", "is", "red." },
				clue = "Begin with “The” and finish with the word that has a full stop.",
				explanation = "“The kite is red.” starts with a capital letter and ends with a full stop.",
			},
			{
				id = "c1-type-action",
				kind = "type",
				title = "Complete the thought",
				skill = "Everyday verbs",
				prompt = "Type one word: I ___ water when I am thirsty.",
				answers = { "drink" },
				placeholder = "One English word",
				clue = "What do you do with water? The word begins with d.",
				explanation = "Drink is the action word: “I drink water when I am thirsty.”",
			},
		},
	},
	{
		class = 2,
		tagline = "Sentences that grow",
		colour = "#d99a2b",
		exercises = {
			{
				id = "c2-choose-plural",
				kind = "choose",
				title = "Choose the plural",
				skill = "One and many",
				prompt = "There are three ___ in the basket.",
				options = { "mango", "mangoes", "mango's" },
				answer = 2,
				clue = "The sentence says there is more than one mango.",
				explanation = "Mangoes means more than one mango. An apostrophe does not make this plural.",
			},
			{
				id = "c2-build-neem-tree",
				kind = "build",
				title = "Put the words in order",
				skill = "Place words",
				prompt = "Drag every card into a sentence that tells where the children play.",
				tokens = { "neem", "We", "tree.", "under", "play", "the" },
				answer = { "We", "play", "under", "the", "neem", "tree." },
				clue = "Who acts comes first. The place comes after “play”.",
				explanation = "“We play under the neem tree.” uses “under” to tell where.",
			},
			{
				id = "c2-type-opposite",
				kind = "type",
				title = "Find the opposite",
				skill = "Word meanings",
				prompt = "The bus was not early; it was ___. Type the missing word.",
				answers = { "late" },
				placeholder = "Opposite of early",
				clue = "The word begins with l and ends with e.",
				explanation = "Late is the opposite of early.",
			},
		},
	},
	{
		class = 3,
		tagline = "Details and time",
		colour = "#2d8a67",
		exercises = {
			{
				id = "c3-choose-describing-word",
				kind = "choose",
				title = "Spot the describing word",
				skill = "Adjectives",
				prompt = "The bright lantern lit the room. Which word describes the lantern?",
				options = { "bright", "lit", "room" },
				answer = 1,
				clue = "Ask: what was the lantern like?",
				explanation = "Bright tells us what the lantern was like, so it is an adjective.",
			},
			{
				id = "c3-build-seed",
				kind = "build",
				title = "Build with detail",
				skill = "Adjective placement",
				prompt = "Drag every word into one sentence.",
				tokens = { "seed.", "tiny", "planted", "Riya", "a" },
				answer = { "Riya", "planted", "a", "tiny", "seed." },
				clue = "Start with the person. Put the describing word just before “seed”.",
				explanation = "“Riya planted a tiny seed.” places the adjective “tiny” beside the noun it describes.",
			},
			{
				id = "c3-type-past-tense",
				kind = "type",
				title = "Move the action to the past",
				skill = "Past tense",
				prompt = "Today I bring my notebook. Yesterday I ___ it too.",
				answers = { "brought" },
				placeholder = "Past form of bring",
				clue = "This past-tense word is not made by adding -ed. It begins with br.",
				explanation = "Brought is the past-tense form of bring.",
			},
		},
	},
	{
		class = 4,
		tagline = "Read between the lines",
		colour = "#3979b7",
		exercises = {
			{
				id = "c4-choose-inference",
				kind = "choose",
				title = "Use clues from the text",
				skill = "Inference",
				prompt = "Meera closed the windows. Dark clouds covered the sky. What did she probably expect?",
				options = { "Rain", "A power cut", "A visitor" },
				answer = 1,
				clue = "Connect the dark clouds with the reason for closing windows.",
				explanation = "Dark clouds are evidence that rain may come, so closing the windows makes sense.",
			},
			{
				id = "c4-build-reason",
				kind = "build",
				title = "Connect a reason",
				skill = "Conjunctions",
				prompt = "Drag the cards into a sentence in which the second part gives the reason.",
				tokens = { "was", "We", "because", "walked", "near.", "home", "the", "market" },
				answer = { "We", "walked", "home", "because", "the", "market", "was", "near." },
				clue = "Put the action first, then use “because” to introduce the reason.",
				explanation = "“Because the market was near” explains why we walked home.",
			},
			{
				id = "c4-type-precise-word",
				kind = "type",
				title = "Choose a precise word",
				skill = "Vocabulary",
				prompt = "After the long match, Kabir was very tired. Replace “very tired” with one word.",
				answers = { "exhausted" },
				placeholder = "One precise English word",
				clue = "The word begins with ex and means extremely tired.",
				explanation = "Exhausted is a precise word for feeling very tired.",
			},
		},
	},
	{
		class = 5,
		tagline = "Ideas with evidence",
		colour = "#7258ad",
		exercises = {
			{
				id = "c5-choose-evidence",
				kind = "choose",
				title = "Choose the strongest evidence",
				skill = "Claims and evidence",
				prompt = "Claim: The library is well used. Which detail supports the claim best?",
				options = {
					"The library walls are blue.",
					"More than 200 books are borrowed each week.",
					"The librarian arrives at eight.",
				},
				answer = 2,
				clue = "Choose the detail that measures how often people use the library.",
				explanation = "Weekly borrowing directly shows frequent use; colour and opening time do not.",
			},
			{
				id = "c5-build-contrast",
				kind = "build",
				title = "Shape a complex sentence",
				skill = "Contrast",
				prompt = "Drag the sentence into order so the opening idea contrasts with what happened.",
				tokens = { "walking.", "the", "Although", "team", "steep,", "kept", "path", "was", "the" },
				answer = { "Although", "the", "path", "was", "steep,", "the", "team", "kept", "walking." },
				clue = "Begin with “Although”. The comma separates the challenge from the response.",
				explanation = "Although introduces a contrast: the steep path made walking hard, yet the team continued.",
			},
			{
				id = "c5-type-linking-word",
				kind = "type",
				title = "Explain the connection",
				skill = "Cohesion",
				prompt = "The tank filled quickly ___ it rained all night. Type the linking word that gives the reason.",
				answers = { "because", "as", "since" },
				placeholder = "A linking word",
				clue = "Use a word that answers “why did the tank fill quickly?”",
				explanation = "Because, as, and since can each introduce the reason in this sentence.",
			},
		},
	},
}

local by_id = {}
for _, level in ipairs(classes) do
	for _, exercise in ipairs(level.exercises) do
		by_id[exercise.id] = exercise
	end
end

return { classes = classes, by_id = by_id }
